### ISSUE TITLE
    if all_embeddings[0].dtype == torch.bfloat16: IndexError: list index out of range

### ISSUE THREAD

**Issue by yuyaxiong** [codefuse-ai/CodeFuse-muAgent#12]
Is there any emb model to suggestion for running the demo? 
if u can offer hf download path would be very nice.
my error is this 
```bash
Traceback (most recent call last):
  File "/data/yuyaxiong/project/demo/demo.py", line 53, in <module>
    cbh.import_code(do_interpret=do_interpret)
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/muagent/codechat/codebase_handler/codebase_handler.py", line 100, in import_code
    code_importer.import_code(static_analysis_res, interpretation, do_interpret=do_interpret)
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/muagent/codechat/codebase_handler/code_importer.py", line 43, in import_code
    self.interpretation_to_db(static_analysis_res, interpretation, do_interpret)
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/muagent/codechat/codebase_handler/code_importer.py", line 141, in interpretation_to_db
    emb = get_embedding(engine=self.embed_config.embed_engine, text_list=interp_list, model_path=self.embed_config.embed_model_path, embedding_device= self.embed_config.model_device, embed_config=self.embed_config)
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/muagent/llm_models/get_embedding.py", line 39, in get_embedding
    emb_res = hfe.get_emb(text_list)
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/muagent/llm_models/huggingface_embedding.py", line 36, in get_emb
    emb_res = self.model.embed_documents(text_list)
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/langchain_huggingface/embeddings/huggingface.py", line 87, in embed_documents
    embeddings = self.client.encode(
  File "/home/yuyaxiong/anaconda3/envs/mu_agent/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 565, in encode
    if all_embeddings[0].dtype == torch.bfloat16:
IndexError: list index out of range

```

**Comment by ccly1996** [comment]
same problem

**Comment by lightislost** [comment]
Sorry, I've just gotten around to this now as I was dealing with matters related to the waitang meetings last week.

could you give your examles codes or tell me which example you try?

**Comment by ccly1996** [comment]
> Sorry, I've just gotten around to this now as I was dealing with matters related to the waitang meetings last week.对不起，我现在才开始讨论这个问题，因为我上周正在处理与 waitang 会议有关的事情。
> 
> could you give your examles codes or tell me which example you try?您能提供您的 Examles 代码或告诉我您尝试的是哪个示例吗？

我使用的是examples/muagent_examples/codechat_example.py这个示例

**Comment by lightislost** [comment]
```bash
# 准备conda环境
conda create -n muagent python=3.9

# 0.0.5
pip install codefuse-muagent
```

```python
# 配置你的test_config.py

import os, openai, base64
from loguru import logger

#
OPENAI_API_BASE = "https://api.openai.com/v1"
os.environ["API_BASE_URL"] = OPENAI_API_BASE
os.environ["OPENAI_API_KEY"] = "sk-xxx"
openai.api_key = "sk-xxx"
os.environ["model_name"] = "gpt-3.5-turbo"
os.environ["model_engine] = "openai"

# 示例
os.environ["embed_model"] = "text2vec-base-chinese"
os.environ["embed_model_path"] = "～/thomas/text2vec-base-chinese"
```



```bash
# 进入文件夹
cd examples/muagent_examples
# 执行代码
python codechat_example.py
```


按照这个方式是能正常运行的。你看看在配置层面有其他差异么？

**Comment by lightislost** [comment]
如果没有其他问题，将在下午6点关闭；后续有问题可重新打开

**Comment by ccly1996** [comment]
目前运行的时候没法解析代码文件，显示
![image](https://github.com/user-attachments/assets/7371e82a-ceb6-4e50-aa8e-ebd03fcaeb50)
然后下面会报错
![image](https://github.com/user-attachments/assets/858a4a93-c7da-4764-831e-051ada1a7f13)

**Comment by lightislost** [comment]
这个是你的notebook没启动起来～/codefuse-muagent/sandbox/pycodebox.py

**Comment by ccly1996** [comment]
是修改当前目录下的sandbox/pycodebox.py吗，我修改之后好像没有新的日志输出

**Comment by ccly1996** [comment]
> ```shell
> python codechat_example.py
> ```

2024-10-10 11:40:10.046 | DEBUG    | muagent.sandbox.pycodebox:start:337 - Traceback (most recent call last):

2024-10-10 11:40:10.047 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/bin/jupyter-notebook", line 7, in <module>

2024-10-10 11:40:10.048 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from notebook.notebookapp import main

2024-10-10 11:40:10.048 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/notebook/notebookapp.py", line 79, in <module>

2024-10-10 11:40:10.048 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from .services.contents.manager import ContentsManager

2024-10-10 11:40:10.048 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/notebook/services/contents/manager.py", line 17, in <module>

2024-10-10 11:40:10.049 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from nbformat import sign, validate as validate_nb, ValidationError

2024-10-10 11:40:10.049 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/nbformat/__init__.py", line 11, in <module>

2024-10-10 11:40:10.049 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from . import v1, v2, v3, v4

2024-10-10 11:40:10.049 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/nbformat/v4/__init__.py", line 39, in <module>

2024-10-10 11:40:10.050 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from .convert import downgrade, upgrade

2024-10-10 11:40:10.050 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/nbformat/v4/convert.py", line 13, in <module>

2024-10-10 11:40:10.050 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from .. import validator

2024-10-10 11:40:10.050 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/nbformat/validator.py", line 15, in <module>

2024-10-10 11:40:10.051 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from .json_compat import ValidationError, _validator_for_name, get_current_validator

2024-10-10 11:40:10.051 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/nbformat/json_compat.py", line 11, in <module>

2024-10-10 11:40:10.051 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     import jsonschema

2024-10-10 11:40:10.051 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/jsonschema/__init__.py", line 13, in <module>

2024-10-10 11:40:10.052 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from jsonschema._format import FormatChecker

2024-10-10 11:40:10.052 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/jsonschema/_format.py", line 11, in <module>

2024-10-10 11:40:10.052 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from jsonschema.exceptions import FormatError

2024-10-10 11:40:10.052 | DEBUG    | muagent.sandbox.pycodebox:start:337 -   File "/home/lvyue/anaconda3/lib/python3.9/site-packages/jsonschema/exceptions.py", line 14, in <module>

2024-10-10 11:40:10.053 | DEBUG    | muagent.sandbox.pycodebox:start:337 -     from attrs import define

2024-10-10 11:40:10.053 | DEBUG    | muagent.sandbox.pycodebox:start:337 - ModuleNotFoundError: No module named 'attrs'

2024-10-10 11:40:10.089 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.090 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.090 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.091 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.091 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.091 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.091 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.092 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.092 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.092 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.092 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.093 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.093 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.093 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.093 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.094 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.094 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.094 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.094 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.094 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.095 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.095 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.095 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.095 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.096 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.096 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.096 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.096 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.097 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.097 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.097 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.097 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.098 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.098 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.098 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.098 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.098 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.099 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.099 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.099 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.099 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.100 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.100 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.100 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.100 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.101 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.101 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.101 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.101 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.102 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.102 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.102 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.102 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.102 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.103 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.103 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.103 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.103 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.104 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.104 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.104 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.104 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.105 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.105 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.105 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.105 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.106 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.107 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.107 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
2024-10-10 11:40:10.107 | DEBUG    | muagent.sandbox.pycodebox:start:337 - 
Traceback (most recent call last):
  File "/data/ly/CodeFuse-muAgent/examples/muagent_examples/codechat_example.py", line 78, in <module>
    phase = BasePhase(
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/muagent/connector/phase/base_phase.py", line 75, in __init__
    self.message_utils = MessageUtils(None, sandbox_server, jupyter_work_path, embed_config, llm_config, kb_root_path, doc_retrieval, code_retrieval, search_retrieval, log_verbose)
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/muagent/connector/message_process.py", line 43, in __init__
    self.codebox = PyCodeBox(
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/muagent/sandbox/pycodebox.py", line 35, in __init__
    self.start()
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/muagent/sandbox/pycodebox.py", line 344, in start
    self._check_connect_success()
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/muagent/sandbox/pycodebox.py", line 275, in _check_connect_success
    raise BaseException(f"can't connect to {self.remote_url}")
BaseException: can't connect to http://127.0.0.1:5050
Close connection to 127.0.0.1:9669 failed:'NoneType' object has no attribute 'close'找到了，这个是报错日志

**Comment by lightislost** [comment]
无法复现你的错误

```bash
# 可以确认下notebook版本
pip list|grep notebook
> notebook                                 7.2.2
> notebook_shim                            0.2.4
```

```确认能否启动notebook服务
jupyter-notebook --NotebookApp.token=mytoken --port=5050 --ServerApp.disable_check_xsrf=True
```

**Comment by ccly1996** [comment]
![image](https://github.com/user-attachments/assets/82c3b5b7-4e75-4380-b017-7989f0f6b377)
jupyter可以启动，版本也跟上述相同，但是运行codechat_example.py又报了这个错误安装了faiss-cpu和faiss-gpu也不行

**Comment by lightislost** [comment]
1、sandbox可以看下 ~CodeFuse-muAgent/tests/sandbox/sandbox_test.py  这个测例看看能不能跑通

2、faiss版本
```
pip list|grep faiss
> faiss-cpu                                1.8.0.post1
```

3、确认下python版本，
```
python --version
> Python 3.9.19
```

**Comment by ccly1996** [comment]
> 1、sandbox可以看下 ~CodeFuse-muAgent/tests/sandbox/sandbox_test.py 这个测例看看能不能跑通
> 
> 2、faiss版本
> 
> ```
> pip list|grep faiss
> > faiss-cpu                                1.8.0.post1
> ```
> 
> 3、确认下python版本，
> 
> ```
> python --version
> > Python 3.9.19
> ```

安装faiss-cpu 1.8.0.post1后执行没有在报错，但是卡在这里没有响应
![image](https://github.com/user-attachments/assets/c55f873a-f4e9-43fa-a72f-d17091f59798)
运行tests/sandbox/sandbox_test.py后显示如下
![image](https://github.com/user-attachments/assets/fe74985a-f436-4ad7-ad15-77e6d4838ae4)

**Comment by lightislost** [comment]
说明sandbox是的正常了。后面那些都不像是报错信息，卡住应该是其他问题，可以自己debug下，提供更多信息

**Comment by ccly1996** [comment]
> 说明sandbox是的正常了。后面那些都不像是报错信息，卡住应该是其他问题，可以自己debug下，提供更多信息

我debug了一下，发现报了一个这个错误Traceback (most recent call last):
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/openai/_base_client.py", line 952, in _request
    response = self._client.send(
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/lvyue/anaconda3/envs/muagent/lib/python3.9/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 101] Network is unreachable

模型配置是
OPENAI_API_BASE = "http://localhost:9997/v1"
os.environ["API_BASE_URL"] = OPENAI_API_BASE
os.environ["OPENAI_API_KEY"] = "sk-xxx"
openai.api_key = "sk-xxx"
os.environ["model_name"] = "gpt-4-32k"
os.environ["model_engine"] = "openai"
这个地址我测试可以使用，但是这里就会报错
